### ISSUE TITLE
ISO is incompatible with qvm-create-windows-qube

### ISSUE THREAD

**Issue by arkenoi** [tabit-pro/qubes-windows-tools-cross#5] opened 2021-10-25 17:27 UTC
Don't know how to diagnose it further, but the build script produced installer that apparently does nothing :( It launches "waiting for shutdown" window and nothing happens, and apparently all previous scrips just exit without actually doing anything, no rexec inside qube and no extra drivers.

**Comment by arkenoi** [comment] 2021-10-25 17:52
Ah. The installer works when launched manually, but something is definitely wrong with autostart.

**Comment by jevank** [comment] 2021-10-25 17:58
What do you mean by autostart? 
qvm-create-windows-qube?

This tool is still incomparable with our build because of MSI package instead of exe.

**Comment by arkenoi** [comment] 2021-10-25 18:00
Ahhh, that makes sense. Yes, also there is something called run.bat and it does not work either.

**Comment by jevank** [comment] 2021-10-25 18:06
There is no such file on our iso, as I remember Elliot Killick's script creates it to automate installation, so look at qvm-create-windows-tools

**Comment by arkenoi** [comment] 2021-10-25 18:08
sorry! just looked inside the script and indeed it creates a modified cdrom image based on the pre-built one. so not your fault at all. I assumed it is the way it was built originally and was wrong.

**Comment by brendanhoar** [comment] 2021-10-27 21:26
Yup, ran into this.

I'm waiting to see if @elliotkillick will accept and/or work with me on my two pending PRs before sending in a PR for the EXE vs. MSI difference. 

In addition, I am doing some debugging of issues with the 4.1.65 tools (here) under Qubes 4.0 as some things are problematic (and may send some PRs here as well). It would be nice to have a single ISO that works in both.

B

**Comment by jevank** [comment] 2021-11-16 09:46
Should we close this issue or rename to compatibility with qvm-create-windows-qube ?

**Comment by brendanhoar** [comment] 2021-11-16 11:18
I'm not the OP, but Elliot accepted the tiny PR that also launches  MSI installers. So I believe this is now resolved.

So, perhaps both update issue name *and* close?

Brendan

**Comment by jevank** [comment] 2021-11-17 07:18
> I'm not the OP, but Elliot accepted the tiny PR that also launches MSI installers. So I believe this is now resolved.

Good news, thanks. I will try it

**Comment by gdanskij** [comment] 2021-12-20 05:43
Hi,

I'm running into compatibility issues with the qvm-create-windows-qube tool still; it appears the ISO generated doesn't mount with the scripts Elliot is using.  Maybe I'm doing something wrong...

**Comment by brendanhoar** [comment] 2021-12-22 04:39
@e6lk7dqzm83p resolved the main QWT issue as per the below. Appears root cause was corrupted ISO.

https://github.com/elliotkillick/qvm-create-windows-qube/issues/39#issuecomment-999243803

B

**Comment by jevank** [comment] 2021-12-22 11:50
Thanks @brendanhoar it works! Tested with win10x64-ltsc-eval.iso
So close it

**Closed as completed by jevank** 2021-12-22 11:50 UTC
